# Generated by Django 3.1 on 2020-10-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_shorten_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorten_urls',
            name='short_url',
            field=models.CharField(max_length=10),
        ),
    ]
