# Generated by Django 3.1 on 2020-10-20 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0008_shorten_urls_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorten_urls',
            name='short_url',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='shorten_urls',
            name='user',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
