# Generated by Django 3.1 on 2020-10-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shorten_Urls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_url', models.CharField(max_length=200)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.keys')),
            ],
        ),
    ]
