# Generated by Django 3.1.1 on 2020-10-18 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0004_shorten_urls_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorten_urls',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shorten_urls',
            name='expiration_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shorten_urls',
            name='expire_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shorten_urls',
            name='updation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shorten_urls',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shorten_urls',
            name='short_url',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
